name: .E2E
on:
  workflow_dispatch:
    inputs:
      frontend-url:
        description: "URL of the application"
        required: true
        type: string
      environment:
        description: "Environment to read secrets from GitHub secrets"
        required: false
        default: dev
        type: string
      timeout-minutes:
        description: "Timeout minutes"
        default: 8
        required: false
        type: number
  workflow_call:
    secrets:
      E2E_AUTO_TEST_USER_NAME:
        required: true
      E2E_AUTO_TEST_PASSWORD:
        required: true
      E2E_AUTO_TEST_OTP_SECRET:
        required: true
    inputs:
      frontend-url:
        description: "URL of the application"
        required: true
        type: string
      environment:
        description: "Environment to read secrets from GitHub secrets"
        required: false
        default: dev
        type: string
      timeout-minutes:
        description: "Timeout minutes"
        default: 8
        required: false
        type: number

jobs:
  end-to-end:
    name: Tests
    environment: ${{ inputs.environment }}
    timeout-minutes: ${{ inputs.timeout-minutes }}
    runs-on: ubuntu-24.04
    strategy:
      max-parallel: 1
      matrix:
        project: [Google Chrome] # [chromium, Google Chrome, firefox, safari, Microsoft Edge]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22
      - name: Install dependencies
        run: npm ci
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        env:
          E2E_AUTO_TEST_BASE_URL: ${{ inputs.frontend-url }}
          E2E_AUTO_TEST_USER_NAME: ${{ secrets.E2E_AUTO_TEST_USER_NAME }}
          E2E_AUTO_TEST_PASSWORD: ${{ secrets.E2E_AUTO_TEST_PASSWORD }}
          E2E_AUTO_TEST_OTP_SECRET: ${{ secrets.E2E_AUTO_TEST_OTP_SECRET }}
        run: npx playwright test --project="${{ matrix.project }}" --reporter=html
      - uses: actions/upload-artifact@v4
        if: always()
        name: upload results
        env:
          PW_TEST_HTML_REPORT_OPEN: always
        with:
          name: playwright-report-${{ matrix.project }}
          path: playwright-report/
          retention-days: 7
